apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-tempo
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        uid: tempo
        url: http://tempo.observability.svc:3100
        jsonData:
          tracesToLogs:
            datasourceUid: P8E80F9AEF21F6940
            filterByTraceID: true
            filterBySpanID: false
            spanStartTimeShift: '-5m'
            spanEndTimeShift: '5m'
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: '-5m'
            spanEndTimeShift: '5m'
          serviceMap:
            datasourceUid: prometheus
        editable: true
