apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Loki
        orgId: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        uid: P8E80F9AEF21F6940
        url: http://loki-gateway.observability.svc.brd-hq-cluster.brd.rw
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"trace_id":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'
            - datasourceUid: tempo
              matcherRegex: '"traceId":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'
        secureJsonData:
          httpHeaderValue1: brd
        editable: true
