export const OBSERVABILITY_CONFIG = Symbol('OBSERVABILITY_CONFIG');
export const OBSERVABILITY_LOGGER = Symbol('OBSERVABILITY_LOGGER');
export const OBSERVABILITY_TRACER = Symbol('OBSERVABILITY_TRACER');
export const OBSERVABILITY_METRICS = Symbol('OBSERVABILITY_METRICS');
